### ISSUE TITLE
java.lang.NullPointerException on TileEntityRFExciter.updateEntity

### ISSUE THREAD

**Issue by joekaiser** [joekaiser/QuantumFlux#24]
OpenEye Reports:

**java.lang.NullPointerException**

    at jotato.quantumflux.tileentity.TileEntityRFExciter.updateEntity(TileEntityRFExciter.java:106)
    at net.minecraft.world.World.updateEntities(World.java:1939)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by joekaiser** [comment]
fixed by 34b63e6
