### ISSUE TITLE
Error on Sliptopia Server

### ISSUE THREAD

**Issue by mercsniper** [joekaiser/QuantumFlux#34]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/9/15 8:50 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: icon_side
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchFieldError: icon_side
        at jotato.quantumflux.machine.cluster.BlockQuibitCluster.<init>(BlockQuibitCluster.java:28)
        at jotato.quantumflux.blocks.ModBlocks.init(ModBlocks.java:49)
        at jotato.quantumflux.QuantumFlux.preInit(QuantumFlux.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
        ... 5 more

 UCH     mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
        UCH     FML{7.10.99.99} [Forge Mod Loader] (ftbserver.jar)
        UCH     Forge{10.13.4.1470} [Minecraft Forge] (ftbserver.jar)

**Comment by joekaiser** [comment]
What were you doing when this happened

**Comment by mercsniper** [comment]
Just trying to start my Sliptopia server. Wouldnt get past initialization. 
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/9/15 9:18 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/nei/api/API
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: codechicken/nei/api/API
        at de.keridos.floodlights.compatability.ModCompatibility.hideNEIItems(ModCompatibility.java:51)
        at de.keridos.floodlights.compatability.ModCompatibility.performModCompat(ModCompatibility.java:65)
        at de.keridos.floodlights.FloodLights.init(FloodLights.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: codechicken.nei.api.API
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 34 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 3.10.0-229.4.2.el7.x86_64
        Java Version: 1.8.0_45, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 1205376584 bytes (1149 MB) / 2076049408 bytes (1979 MB) up to 5189795840 bytes (4949 MB)
        JVM Flags: 10 total; -Xms2G -Xmx5G -XX:PermSize=768m -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -Xmx5120M
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 106 mods loaded, 106 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHI    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
        UCHI    FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar)
        UCHI    Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar)
        UCHI    appliedenergistics2-core{rv2-stable-4} [AppliedEnergistics2 Core] (minecraft.jar)
        UCHI    Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar)
        UCHI    CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar)
        UCHI    ExtraFixes{1.2.4b} [Extra Fixes] (minecraft.jar)
        UCHI    ImmibisMicroblocks{59.1.0} [Immibis's Microblocks] (immibis-microblocks-59.1.0.jar)
        UCHI    LanteaCraft-Core{1.0} [LanteaCraft Core] (minecraft.jar)
        UCHI    MobiusCore{1.2.5} [MobiusCore] (minecraft.jar)
        UCHI    OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar)
        UCHI    <CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
        UCHI    battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar)
        UCHI    appliedenergistics2{rv2-stable-4} [Applied Energistics 2] (appliedenergistics2-rv2-stable-4.jar)
        UCHI    bdlib{1.8.1.87} [BD Lib] (bdlib-1.8.1.87-mc1.7.10.jar)
        UCHI    ae2stuff{0.3.1.33} [AE2 Stuff] (ae2stuff-0.3.1.33-mc1.7.10.jar)
        UCHI    nevermine{2.3} [AdventOfAscension] (AoA-2.3.1.jar)
        UCHI    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar)
        UCHI    Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar)
        UCHI    Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar)
        UCHI    Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar)
        UCHI    Artifacts{1.1.1} [Artifacts] (Artifacts-1.1.1.jar)
        UCHI    BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar)
        UCHI    Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar)
        UCHI    Botania{r1.6-191} [Botania] (Botania r1.6-191.jar)
        UCHI    CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar)
        UCHI    ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar)
        UCHI    ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar)
        UCHI    chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar)
        UCHI    CoFHCore{1.7.10R3.0.3B2} [CoFH Core] (CoFHCore-[1.7.10]3.0.3B2-294.jar)
        UCHI    lootablebodies{1.3.5} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.3.5-backport.jar)
        UCHI    props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar)
        UCHI    ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar)
        UCHI    ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar)
        UCHI    DraconicEvolution{1.0.1c} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.1c.jar)
        UCHI    MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip)
        UCHI    Emotes{1.0} [Emotes] (Emotes 1.0.jar)
        UCHI    Enchiridion{1.1} [Enchiridion] (Enchiridion 2-1.7.10-2.0.1.jar)
        UCHI    Enchiridion2{2.0.1} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.1.jar)
        UCHI    MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    Mekanism{8.1.3} [Mekanism] (Mekanism-1.7.10-8.1.3.231.jar)
        UCHI    EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar)
        UCHI    EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar)
        UCHI    EnderTech{1.7.10-0.3.2.388} [EnderTech] (EnderTech-1.7.10-0.3.2.388.jar)
        UCHI    EnderZoo{1.7.10-1.0.11.28} [Ender Zoo] (EnderZoo-1.7.10-1.0.11.28.jar)
        UCHI    extrabuttons{1.7.10.1} [ExtraButtons] (ExtraButtons-1.7.10.1.jar)
        UCHI    Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar)
        UCHI    extracells{2.2.71} [Extra Cells 2] (ExtraCells-1.7.10-2.2.71b121.jar)
        UCHI    ExtraUtilities{1.2.5} [Extra Utilities] (extrautilities-1.2.5.jar)
        UCHI    FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar)
        UCHI    fastleafdecay{1.1} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.1.jar)
        UCHI    flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar)
        UCHI    FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar)
        UCHE    FloodLights{0.4.3} [Flood Lights] (FloodLights-1.7.10-0.4.3-62.jar)
        UCHI    ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar)
        UCHI    ganyssurface{1.11.1} [Gany's Surface] (Ganys Surface-1.11.1.jar)
        UCHI    GardenCore{1.7.10-1.6.3} [Garden Core] (GardenStuff-1.7.10-1.6.3.jar)
        UCHI    GardenContainers{1.7.10-1.6.3} [Garden Containers] (GardenStuff-1.7.10-1.6.3.jar)
        UCHI    GardenStuff{1.7.10-1.6.3} [Garden Stuff] (GardenStuff-1.7.10-1.6.3.jar)
        UCHI    GardenTrees{1.7.10-1.6.3} [Garden Trees] (GardenStuff-1.7.10-1.6.3.jar)
        UCHI    iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar)
        UCHI    ImmibisCore{59.1.1} [Immibis Core] (immibis-core-59.1.1.jar)
        UCHI    LanteaCraft{1.0.0-70} [LanteaCraft] (LanteaCraft-1.7.10-70.jar)
        UCHI    LightSabers{1.0.0} [LightSabers] (LightSabersMod v1.0.0 (MineCraft 1.7.10).zip)
        UCHI    magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.2-0.11.jar)
        UCHI    MekanismGenerators{8.1.3} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.3.231.jar)
        UCHI    MekanismTools{8.1.3} [MekanismTools] (MekanismTools-1.7.10-8.1.3.231.jar)
        UCHI    mfrmagiccropscompat{1.1} [MinefactoryReloaded & MagicalCrops extra compatibility] (minefactory-magicalcrops-compatibility-1.1.jar)
        UCHI    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar)
        UCHI    cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar)
        UCHI    MultiPageChest{1.3.4} [Multi Page Chest] (MultiPageChest-1.3.4-MC1.7.10.jar)
        UCHI    NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar)
        UCHI    Oceancraft{1.4.1} [Oceancraft] (Oceancraft-1.4.1.jar)
        UCHI    OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar)
        UCHI    OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar)
        UCHI    JotatosPracticalities{0.6.2} [Practicalities] (practicalities-1.7.10-0.6.2.jar)
        UCHI    StorageDrawers{1.7.10-1.5.4} [Storage Drawers] (StorageDrawers-1.7.10-1.5.4.jar)
        UCHI    thaumicenergistics{0.8.10.5} [Thaumic Energistics] (thaumicenergistics-0.8.10.5.jar)
        UCHI    ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar)
        UCHI    Torcherino{2.2s} [Torcherino] (Torcherino-1.7.10-2.2s.jar)
        UCHI    ttCore{MC1.7.10-0.1.0-67} [ttCore] (ttCore-MC1.7.10-0.1.0-67.jar)
        UCHI    WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar)
        UCHI    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar)
        UCHI    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar)
        UCHI    Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar)
        UCHI    McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar)
        UCHI    technom{0.10.0} [Technomancy] (Technomancy - 0.10.l - 1.7.10.jar)
        UCHI    ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar)
        OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:ENABLED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
        Class transformer null safety: all safe
        AE2 Version: stable rv2-stable-4 for Forge 10.13.2.1291
        CoFHCore: -[1.7.10]3.0.3B2-294
        ThermalFoundation: -[1.7.10]1.0.0-81
        ThermalExpansion: -[1.7.10]4.0.1-182
        MineFactoryReloaded: -[1.7.10]2.8.0-104
        NetherOres: -[1.7.10]2.3.0-12
        ThermalDynamics: -[1.7.10]1.0.0-122
        List of loaded APIs:
                * appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-4.jar
                * BattlePlayer (0.1) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar
                * Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
                * BotaniaAPI (50) from Botania r1.6-191.jar
                * BuildCraftAPI|core (1.0) from extrautilities-1.2.5.jar
                * BuildCraftAPI|tools (1.0) from extrautilities-1.2.5.jar
                * ChiselAPI (0.0.2) from Chisel2-2.3.10.37.jar
                * ChiselAPI|Carving (0.0.2) from Chisel2-2.3.10.37.jar
                * CoFHAPI (1.7.10R1.0.2) from Draconic-Evolution-1.7.10-1.0.1c.jar
                * CoFHAPI|block (1.7.10R1.0.12) from Technomancy - 0.10.l - 1.7.10.jar
                * CoFHAPI|core (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.3B2-169.jar
                * CoFHAPI|energy (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.3B2-169.jar
                * CoFHAPI|fluid (1.7.10R1.0.13B1) from CoFHCore-[1.7.10]3.0.3B2-294.jar
                * CoFHAPI|inventory (1.7.10R1.0.13B1) from CoFHCore-[1.7.10]3.0.3B2-294.jar
                * CoFHAPI|item (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
                * CoFHAPI|modhelpers (1.7.10R1.0.13B1) from CoFHCore-[1.7.10]3.0.3B2-294.jar
                * CoFHAPI|tileentity (1.7.10R1.0.7) from EnderTech-1.7.10-0.3.2.388.jar
                * CoFHAPI|transport (1.7.10R1.0.13B1) from CoFHCore-[1.7.10]3.0.3B2-294.jar
                * CoFHAPI|world (1.7.10R1.0.7) from EnderTech-1.7.10-0.3.2.388.jar
                * CoFHLib (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
                * CoFHLib|audio (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.3B2-169.jar
                * CoFHLib|gui (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
                * CoFHLib|gui|container (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.3B2-169.jar
                * CoFHLib|gui|element (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
                * CoFHLib|gui|element|listbox (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.388.jar
                * CoFHLib|gui|slot (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
                * CoFHLib|inventory (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.3B2-169.jar
                * CoFHLib|render (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.388.jar
                * CoFHLib|render|particle (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.3B2-169.jar
                * CoFHLib|util (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
                * CoFHLib|util|helpers (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
                * CoFHLib|util|position (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.388.jar
                * CoFHLib|world (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
                * CoFHLib|world|feature (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.388.jar
                * CSLib|API (1.0) from Decocraft-2.0.2_1.7.10.jar
                * DraconicEvolution|API (1.0) from Draconic-Evolution-1.7.10-1.0.1c.jar
                * DualWield (0.1) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar
                * EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
                * EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
                * EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
                * GardenCoreAPI (1.0.0) from GardenStuff-1.7.10-1.6.3.jar
                * Heraldry (alpha) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar
                * MekanismAPI|core (8.0.0) from Mekanism-1.7.10-8.1.3.231.jar
                * MekanismAPI|energy (8.0.0) from Mekanism-1.7.10-8.1.3.231.jar
                * MekanismAPI|gas (8.0.0) from Mekanism-1.7.10-8.1.3.231.jar
                * MekanismAPI|infuse (8.0.0) from Mekanism-1.7.10-8.1.3.231.jar
                * MekanismAPI|laser (8.0.0) from Mekanism-1.7.10-8.1.3.231.jar
                * MekanismAPI|reactor (8.0.0) from Mekanism-1.7.10-8.1.3.231.jar
                * MekanismAPI|recipe (8.0.0) from Mekanism-1.7.10-8.1.3.231.jar
                * MekanismAPI|transmitter (8.0.0) from Mekanism-1.7.10-8.1.3.231.jar
                * MekanismAPI|util (8.0.0) from Mekanism-1.7.10-8.1.3.231.jar
                * OpenBlocks|API (1.0) from OpenBlocks-1.7.10-1.4.3.jar
                * Quiver (0.2) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar
                * Shield (0.1) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar
                * Thaumcraft|API (4.2.2.0) from Thaumcraft-1.7.10-4.2.3.5.jar
                * WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
                * Weapons (0.1) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar
        Profiler Position: N/A (disabled)
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)[root@minecraft crash-reports]#

**Comment by joekaiser** [comment]
What modifications (if any) did you make to the pack?

**Comment by mercsniper** [comment]
disabled client based stuff, otherwise none.

**Comment by joekaiser** [comment]
I think you may have disabled a few wrong mods. The crash logs don't even make sense. The first one is about QF and the second is NEI.  Can you list the mods you disabled?

**Comment by mercsniper** [comment]
CustomMainMenu-MC1.7.10-1.5.jar.disabled
InventoryTweaks-1.58-147.jar.disabled
liteloader-1.7.10.jardisabled
MobiusCore-1.2.5_1.7.10.jar.disabled
OptiFine_1.7.10_HD_B6.jar.disabled
QuantumFlux-1.7.10-1.2.2.jar.disabled
ResourceLoader-1.2.jar.disabled
tcnodetracker-1.7.10-1.1.1.jar.disabled
thaumcraftneiplugin-1.7.10-1.7.jar.disabled
WailaHarvestability-mc1.7.x-1.1.2.jar.disabled
WAILAPlugins-MC1.7.10-0.0.1-15.jar.disabled
