### ISSUE TITLE
[1.3.2-b2] Server is crashing with NPE on the RFExciter

### ISSUE THREAD

**Issue by joekaiser** [joekaiser/QuantumFlux#71]
**java.lang.NullPointerException:** 

    at jotato.quantumflux.machine.exciter.TileEntityRFExciter.updateEntity(TileEntityRFExciter.java:113)
    at net.minecraft.world.World.updateEntities(World.java:1939)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by joekaiser** [comment]
I don't know *how* this happened, but e2eb3cd will prevent a hard crash
